// Copyright (c) 2023 - 2026 Restate Software, Inc., Restate GmbH.
// All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use crate::table_macro::*;

use datafusion::arrow::datatypes::DataType;

define_sort_order!(sys_invocation(partition_key, id));

define_table!(sys_invocation(
    /// Internal column that is used for partitioning the services invocations. Can be ignored.
    partition_key: DataType::UInt64,

    /// [Invocation ID](/operate/invocation#invocation-identifier).
    id: DataType::LargeUtf8,

    /// Invocation Target. Format for plain services: `ServiceName/HandlerName`, e.g.
    /// `Greeter/greet`. Format for virtual objects/workflows: `VirtualObjectName/Key/HandlerName`,
    /// e.g. `Greeter/Francesco/greet`.
    target: DataType::LargeUtf8,

    /// The name of the invoked service.
    target_service_name: DataType::LargeUtf8,

    /// The key of the virtual object or the workflow ID. Null for regular services.
    target_service_key: DataType::LargeUtf8,

    /// The invoked handler.
    target_handler_name: DataType::LargeUtf8,

    /// The service type. Either `service` or `virtual_object` or `workflow`.
    target_service_ty: DataType::LargeUtf8,

    /// Idempotency key, if any.
    idempotency_key: DataType::LargeUtf8,

    /// Either:
    /// * `ingress` if the invocation was created externally.
    /// * `service` if the invocation was created by another Restate service.
    /// * `subscription` if the invocation was created by a subscription (e.g. Kafka).
    /// * `restart_as_new` if the invocation was created by restarting an old invocation as new.
    invoked_by: DataType::LargeUtf8,

    /// The name of caller service if `invoked_by = 'service'`.
    invoked_by_service_name: DataType::LargeUtf8,

    /// The caller [Invocation ID](/operate/invocation#invocation-identifier) if `invoked_by = 'service'`.
    invoked_by_id: DataType::LargeUtf8,

    /// The subscription id if `invoked_by = 'subscription'`.
    invoked_by_subscription_id: DataType::LargeUtf8,

    /// The caller invocation target if `invoked_by = 'service'`.
    invoked_by_target: DataType::LargeUtf8,

    /// The original invocation id if `invoked_by = 'restart_as_new'`.
    restarted_from: DataType::LargeUtf8,

    /// The ID of the service deployment that started processing this invocation, and will continue
    /// to do so (e.g. for retries). This gets set after the first journal entry has been stored for
    /// this invocation.
    pinned_deployment_id: DataType::LargeUtf8,

    /// The negotiated protocol version used for this invocation.
    /// This gets set after the first journal entry has been stored for this invocation.
    pinned_service_protocol_version: DataType::UInt32,

    /// The ID of the trace that is assigned to this invocation. Only relevant when tracing is
    /// enabled.
    trace_id: DataType::LargeUtf8,

    /// The number of journal entries durably logged for this invocation.
    journal_size: DataType::UInt32,

    /// The number of commands generated by this invocation, stored in the journal.
    /// Only relevant when pinned_service_protocol_version >= 4.
    journal_commands_size: DataType::UInt32,

    /// Timestamp indicating the start of this invocation.
    created_at: TimestampMillisecond,

    /// restate-server version in use when this invocation was created.
    created_using_restate_version: DataType::LargeUtf8,

    /// Timestamp indicating the last invocation status transition. For example, last time the
    /// status changed from `invoked` to `suspended`.
    modified_at: TimestampMillisecond,

    /// Timestamp indicating when the invocation was inboxed, if ever.
    inboxed_at: TimestampMillisecond,

    /// Timestamp indicating when the invocation was scheduled, if ever.
    scheduled_at: TimestampMillisecond,

    /// If the invocation was scheduled, indicates the timestamp when the invocation should start.
    scheduled_start_at: TimestampMillisecond,

    /// Timestamp indicating when the invocation first transitioned to running, if ever.
    running_at: TimestampMillisecond,

    /// Timestamp indicating when the invocation was completed, if ever.
    completed_at: TimestampMillisecond,

    /// For how long the metadata of this invocation, including its result, is retained after completion.
    completion_retention: DataType::Duration,

    /// For how long the journal is retained after completion.
    journal_retention: DataType::Duration,

    /// List of completion ids the invocation is awaiting on, if `status = suspended`.
    suspended_waiting_for_completions: UInt32List,

    /// List of signals the invocation is awaiting on, if `status = suspended`.
    suspended_waiting_for_signals: UInt32List,

    /// The number of invocation attempts since the current leader started executing it. Increments
    /// on start, so a value greater than 1 means a failure occurred. Note: the value is not a
    /// global attempt counter across invocation suspensions and leadership changes.
    retry_count: DataType::UInt64,

    /// Timestamp indicating the start of the most recent attempt of this invocation.
    last_start_at: TimestampMillisecond,

    /// Timestamp indicating the start of the next attempt of this invocation.
    next_retry_at: TimestampMillisecond,

    /// The ID of the service deployment that executed the most recent attempt of this invocation;
    /// this is set before a journal entry is stored, but can change later.
    last_attempt_deployment_id: DataType::LargeUtf8,

    /// Server/SDK version, e.g. `restate-sdk-java/1.0.1`
    last_attempt_server: DataType::LargeUtf8,

    /// An error message describing the most recent failed attempt of this invocation, if any.
    last_failure: DataType::LargeUtf8,

    /// The error code of the most recent failed attempt of this invocation, if any.
    last_failure_error_code: DataType::LargeUtf8,

    /// The index of the journal entry that caused the failure, if any. It may be out-of-bound
    /// of the currently stored entries in `sys_journal`.
    /// DEPRECATED: you should not use this field anymore, but last_failure_related_command_index instead.
    last_failure_related_entry_index: DataType::UInt64,

    /// The name of the journal entry that caused the failure, if any.
    /// DEPRECATED: you should not use this field anymore, but last_failure_related_command_name instead.
    last_failure_related_entry_name: DataType::LargeUtf8,

    /// The type of the journal entry that caused the failure, if any. You can check all the
    /// available entry types in [`entries.rs`](https://github.com/restatedev/restate/blob/main/crates/types/src/journal/entries.rs).
    /// DEPRECATED: you should not use this field anymore, but last_failure_related_command_type instead.
    last_failure_related_entry_type: DataType::LargeUtf8,

    /// The index of the command in the journal that caused the failure, if any. It may be out-of-bound
    /// of the currently stored commands in `sys_journal`.
    last_failure_related_command_index: DataType::UInt64,

    /// The name of the command that caused the failure, if any.
    last_failure_related_command_name: DataType::LargeUtf8,

    /// The type of the command that caused the failure, if any. You can check all the
    /// available command types in [`entries.rs`](https://github.com/restatedev/restate/blob/main/crates/types/src/journal_v2/command.rs).
    last_failure_related_command_type: DataType::LargeUtf8,

    /// The status of the invocation: `pending`, `scheduled`, `ready`, `running`,
    /// `backing-off`, `suspended`, `paused`, or `completed`.
    status: DataType::LargeUtf8,

    /// If `status = 'completed'`, this contains either `success` or `failure`
    completion_result: DataType::LargeUtf8,

    /// If `status = 'completed' AND completion_result = 'failure'`, this contains the error cause
    completion_failure: DataType::LargeUtf8,
));
