#!/usr/bin/env bash
#
# Copyright (c) 2023 - 2025 Restate Software, Inc., Restate GmbH.
# All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.
#

set -e

COMMITTED_CRATE_VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[] | select(.name == "restate-web-ui") | .version')
COMMITTED_CRATE_SHA256_CHECKSUM=$(curl -sSL https://raw.githubusercontent.com/restatedev/restate-web-ui-crate/refs/heads/main/assets/ui-v$COMMITTED_CRATE_VERSION.zip | shasum -a 256 | awk '{print $1}')
echo "Committed artifact for $COMMITTED_CRATE_VERSION has SHA256 checksum of $COMMITTED_CRATE_SHA256_CHECKSUM"

PUBLISHED_SHA256_CHECKSUM=$(curl -sSL https://github.com/restatedev/restate-web-ui/releases/download/v$COMMITTED_CRATE_VERSION/ui-v$COMMITTED_CRATE_VERSION.zip | shasum -a 256 | awk '{print $1}')
echo "Published artifact for $COMMITTED_CRATE_VERSION has SHA256 checksum of $PUBLISHED_SHA256_CHECKSUM"

if [ "$COMMITTED_CRATE_SHA256_CHECKSUM" != "$PUBLISHED_SHA256_CHECKSUM" ]; then
    echo "❌ The committed artifact cannot be verified."
    exit 1
else
    echo "✅ The committed artifact is verified."
fi
