{
 "title": "Invoker concurrency dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Rocksdb reads and writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(restate_rocksdb_bytes_written_total[$__rate_interval])",
     "legendFormat": "Writes {{db}}"
    },
    {
     "expr": "rate(restate_rocksdb_bytes_read_total[$__rate_interval])",
     "legendFormat": "Reads {{db}}"
    }
   ]
  },
  {
   "title": "Invoker task duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "restate_invoker_task_duration_seconds",
     "legendFormat": "Quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "Invocation count (through SQL)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "restate_invocations_total{status!=\"completed\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests and invoker slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "restate_invoker_available_slots",
     "legendFormat": "Invoker available slots"
    },
    {
     "expr": "vertx_http_server_active_requests{method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Live threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 22 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PP Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "restate_partition_applied_lsn_lag",
     "legendFormat": "{{partition}}"
    }
   ]
  }
 ]
}