// Copyright (c) 2023 - 2026 Restate Software, Inc., Restate GmbH.
// All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use std::future::Future;
use std::pin::Pin;
use std::time::Instant;

use anyhow::{Result, bail};
use arrow::error::ArrowError;
use arrow::util::display::ArrayFormatter;
use arrow::util::display::FormatOptions;
use cling::prelude::*;
use comfy_table::Cell;
use comfy_table::Table;

use restate_cli_util::CliContext;
use restate_cli_util::c_eprintln;
use restate_cli_util::c_print;
use restate_cli_util::c_println;
use restate_cli_util::ui::console::Styled;
use restate_cli_util::ui::console::StyledTable;
use restate_cli_util::ui::stylesheet::Style;
use restate_cli_util::ui::watcher::Watch;

use crate::cli_env::CliEnv;
use crate::clients::{DataFusionHttpClient, QueryEngine};
use crate::error::RestateCliError;
use crate::ui::fmt::{Field, Formatter, IfEmpty, IncludeFormatting, OutputFormatter};

// Embedded SQL introspection reference, generated by `cargo xtask generate-cli-sql-tables`.
// Defines `SqlColumnDoc`, `SqlTableDoc`, `SQL_TABLES` and `SQL_TABLES_HELP`.
// TODO: checking in a generated file is a stopgap. Generating it in `build.rs` would need
//  restate-storage-query-datafusion as a build-dependency, which drags restate-core into the host
//  build (breaks cross-compilation, see restate-core's tokio/taskdump). Consider splitting the
//  table schemas/docs into a lightweight crate the CLI can depend on directly.
include!("sql_tables.rs");

/// Run SQL queries to introspect Restate: invocations, journals, state, ...
///
/// Queries the server's introspection tables with ANSI SQL.
/// By default, the output is a table, use `--json` for json array output or `--jsonl` for newline delimited json.
/// Use `restate sql describe <table>` to read individual tables documentation.
#[derive(Parser, Collect, Clone)]
#[command(args_conflicts_with_subcommands = true)]
#[command(after_help = sql_after_help(false), after_long_help = sql_after_help(true))]
pub struct Sql {
    /// The SQL query to run, e.g. "SELECT * FROM sys_invocation LIMIT 10". Required unless
    /// running a subcommand
    query: Option<String>,

    #[command(subcommand)]
    sub: Option<SqlSub>,

    #[clap(flatten)]
    watch: Watch,

    /// Print the rows as line-delimited JSON (one object per line) instead of a table.
    /// Unlike --json, works with -w
    #[arg(long, alias = "ldjson")]
    pub jsonl: bool,

    /// Query engine to run the query on. Defaults to the server's default engine; the
    /// engine that served the query is reported with the row count.
    #[arg(long, value_enum)]
    pub engine: Option<QueryEngine>,
}

/// Examples and docs link, plus the list of tables in the long help.
fn sql_after_help(long: bool) -> String {
    let examples = after_help!(
        examples: [
            "restate sql \"SELECT id, target FROM sys_invocation ORDER BY created_at DESC LIMIT 10\" --json",
            "# State of the Cart virtual object: service_key is the object key, key the state key",
            "restate sql \"SELECT service_key, key, value_utf8 FROM state WHERE service_name = 'Cart'\"",
            "# Compare the experimental distributed query engine against the default one",
            "restate sql \"SELECT COUNT(*) FROM sys_invocation\" --engine v2",
            "restate sql describe sys_invocation",
        ],
        learn_more: "https://docs.restate.dev/references/sql-introspection",
    );
    if long {
        // The generated table list starts with its own heading line.
        let (title, tables) = SQL_TABLES_HELP
            .split_once('\n')
            .unwrap_or((SQL_TABLES_HELP, ""));
        format!("{}\n{tables}\n\n{examples}", crate::help::heading(title))
    } else {
        examples.to_owned()
    }
}

#[derive(Subcommand, Clone)]
enum SqlSub {
    /// Describe the columns of a SQL introspection table: name, type and description.
    #[command(after_help = after_help!(
        examples: [
            "restate sql describe sys_invocation --json",
        ],
        learn_more: "https://docs.restate.dev/references/sql-introspection",
    ))]
    Describe {
        /// The table to describe, e.g. `sys_invocation` (see `restate sql --help` for the list)
        table: String,
    },
}

// We implement cling's `Run` manually instead of `#[derive(Run)]`: the derive
// cannot dispatch an `Option<Subcommand>` field (it would require an orphan
// `impl Run for Option<SqlSub>`, and it also forbids fields after the subcommand
// field). We only need to run the `run_sql` handler; subcommand dispatch is done
// by hand inside it.
impl Run for Sql {
    fn call<'a>(
        &'a self,
        args: &'a mut cling::_private::CollectedArgs,
    ) -> Pin<Box<dyn Future<Output = std::result::Result<(), CliError>> + Send + 'a>> {
        Box::pin(async move {
            use cling::_private::*;
            // Make `&Sql` available to the handler, then run it. The handler's
            // effect is `()`; run it (releasing the borrow of `args`) before
            // applying the effect back.
            args.insert(self.clone(), false);
            Handler::call(run_sql, args)?.into_effect().await?;
            ().apply_effect(args);
            Ok(())
        })
    }
}

async fn run_sql(State(env): State<CliEnv>, opts: &Sql) -> Result<()> {
    match &opts.sub {
        Some(SqlSub::Describe { table }) => run_describe(table),
        None => {
            let Some(query) = opts.query.as_deref() else {
                bail!(
                    "No SQL query provided. Pass a query, e.g. \
                     `restate sql \"SELECT * FROM sys_invocation\"`, or use a subcommand: \
                     `restate sql describe <table>` (see `restate sql --help` for the tables)."
                );
            };
            opts.watch.run(|| run_query(&env, opts, query)).await
        }
    }
}

async fn run_query(env: &CliEnv, sql_opts: &Sql, query: &str) -> Result<()> {
    let client = DataFusionHttpClient::new(env)
        .await?
        .with_query_engine(sql_opts.engine);
    let start_time = Instant::now();
    let resp = client.run_arrow_query(query.to_owned()).await?;

    let json_output = CliContext::get().json_output();
    let mut row_count: usize = 0;

    if sql_opts.jsonl {
        // Buffer the output and print it through the broken-pipe-safe console
        // macros so that e.g. `restate sql "..." --jsonl | head` doesn't error.
        let mut buf = Vec::new();
        let mut writer = arrow::json::LineDelimitedWriter::new(&mut buf);
        for batch in &resp.batches {
            row_count += batch.num_rows();
            writer.write_batches(&[batch])?;
        }
        writer.finish()?;
        c_print!("{}", std::str::from_utf8(&buf)?);
    } else if json_output {
        let mut buf = Vec::new();
        let mut writer = arrow::json::ArrayWriter::new(&mut buf);
        for batch in &resp.batches {
            row_count += batch.num_rows();
            writer.write_batches(&[batch])?;
        }
        writer.finish()?;
        c_print!("{}", std::str::from_utf8(&buf)?);
    } else {
        let mut table = Table::new_styled();
        table.set_styled_header(
            resp.schema
                .fields()
                .iter()
                .map(|col| col.name().to_uppercase())
                .collect::<Vec<String>>(),
        );

        let format_options = FormatOptions::default().with_display_error(true);
        for batch in &resp.batches {
            let formatters = batch
                .columns()
                .iter()
                .map(|c| ArrayFormatter::try_new(c.as_ref(), &format_options))
                .collect::<Result<Vec<_>, ArrowError>>()?;

            for row in 0..batch.num_rows() {
                let mut cells = Vec::new();
                for formatter in &formatters {
                    cells.push(Cell::new(formatter.value(row)));
                }
                table.add_row(cells);
            }
        }

        row_count = table.row_count();
        // Only print if there are actual results.
        if row_count > 0 {
            c_println!("{}", table);
            c_println!();
        }
    }

    let engine = resp
        .engine
        .as_deref()
        .map(|engine| format!(" on query engine {engine}"))
        .unwrap_or_default();
    c_eprintln!(
        "{} rows. Query took {:?}{}",
        row_count,
        Styled(Style::Notice, start_time.elapsed()),
        Styled(Style::Notice, engine)
    );
    Ok(())
}

fn run_describe(table_name: &str) -> Result<()> {
    let Some(doc) = SQL_TABLES.iter().find(|t| t.name == table_name) else {
        let valid = SQL_TABLES
            .iter()
            .map(|t| t.name)
            .collect::<Vec<_>>()
            .join(", ");
        return Err(RestateCliError::not_found(format!(
            "Unknown table '{table_name}'. Valid tables: {valid}"
        ))
        .into());
    };

    let rows: Vec<Vec<Field>> = doc
        .columns
        .iter()
        .map(|c| {
            vec![
                Field::new(c.name),
                Field::new(c.ty),
                Field::new(c.description),
            ]
        })
        .collect();

    let mut f = Formatter::new();
    f.detail(
        "table",
        &[
            ("name", Field::new(doc.name)),
            ("description", Field::new(doc.description)),
        ],
    );
    f.table(
        "columns",
        &["name", "type", "description"],
        &rows,
        IfEmpty::Nothing,
    );
    f.next_step(
        &format!("restate sql \"SELECT * FROM {} LIMIT 10\"", doc.name),
        "sample its rows",
        IncludeFormatting::Yes,
    );
    f.finish()
}
