// Copyright (c) 2023 - 2026 Restate Software, Inc., Restate GmbH.
// All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use std::future::Future;
use std::pin::Pin;
use std::time::Instant;

use anyhow::{Result, bail};
use arrow::error::ArrowError;
use arrow::util::display::ArrayFormatter;
use arrow::util::display::FormatOptions;
use cling::prelude::*;
use comfy_table::Cell;
use comfy_table::Table;
use serde::Serialize;

use restate_cli_util::CliContext;
use restate_cli_util::c_eprintln;
use restate_cli_util::c_print;
use restate_cli_util::c_println;
use restate_cli_util::ui::console::Styled;
use restate_cli_util::ui::console::StyledTable;
use restate_cli_util::ui::stylesheet::Style;
use restate_cli_util::ui::watcher::Watch;

use crate::cli_env::CliEnv;
use crate::ui::fmt::{Field, Formatter, ListItem, OutputFormatter};

// Embedded SQL introspection reference generated by `build.rs`.
// Defines `SqlColumnDoc`, `SqlTableDoc`, `SQL_TABLES` and `SQL_TABLES_HELP`.
include!(concat!(env!("OUT_DIR"), "/sql_tables.rs"));

#[derive(Parser, Collect, Clone)]
#[command(args_conflicts_with_subcommands = true)]
#[command(after_long_help = SQL_TABLES_HELP)]
pub struct Sql {
    /// The SQL query to run.
    query: Option<String>,

    #[command(subcommand)]
    sub: Option<SqlSub>,

    #[clap(flatten)]
    watch: Watch,

    /// Print result as line delimited json instead of using the tabular format
    #[arg(long, alias = "ldjson")]
    pub jsonl: bool,
}

#[derive(Subcommand, Clone)]
enum SqlSub {
    /// List the queryable SQL introspection tables
    Tables,
    /// Describe the columns of a SQL introspection table
    Describe {
        /// The table to describe
        table: String,
    },
}

// We implement cling's `Run` manually instead of `#[derive(Run)]`: the derive
// cannot dispatch an `Option<Subcommand>` field (it would require an orphan
// `impl Run for Option<SqlSub>`, and it also forbids fields after the subcommand
// field). We only need to run the `run_sql` handler; subcommand dispatch is done
// by hand inside it.
impl Run for Sql {
    fn call<'a>(
        &'a self,
        args: &'a mut cling::_private::CollectedArgs,
    ) -> Pin<Box<dyn Future<Output = std::result::Result<(), CliError>> + Send + 'a>> {
        Box::pin(async move {
            use cling::_private::*;
            // Make `&Sql` available to the handler, then run it. The handler's
            // effect is `()`; run it (releasing the borrow of `args`) before
            // applying the effect back.
            args.insert(self.clone(), false);
            Handler::call(run_sql, args)?.into_effect().await?;
            ().apply_effect(args);
            Ok(())
        })
    }
}

async fn run_sql(State(env): State<CliEnv>, opts: &Sql) -> Result<()> {
    match &opts.sub {
        Some(SqlSub::Tables) => run_tables(),
        Some(SqlSub::Describe { table }) => run_describe(table),
        None => {
            let Some(query) = opts.query.as_deref() else {
                bail!(
                    "No SQL query provided. Pass a query, e.g. \
                     `restate sql \"SELECT * FROM sys_invocation\"`, or use a subcommand: \
                     `restate sql tables`, `restate sql describe <table>`."
                );
            };
            opts.watch.run(|| run_query(&env, opts, query)).await
        }
    }
}

async fn run_query(env: &CliEnv, sql_opts: &Sql, query: &str) -> Result<()> {
    let client = crate::clients::DataFusionHttpClient::new(env).await?;
    let start_time = Instant::now();
    let resp = client.run_arrow_query(query.to_owned()).await?;

    let json_output = CliContext::get().json_output();
    let mut row_count: usize = 0;

    if sql_opts.jsonl {
        // Buffer the output and print it through the broken-pipe-safe console
        // macros so that e.g. `restate sql "..." --jsonl | head` doesn't error.
        let mut buf = Vec::new();
        let mut writer = arrow::json::LineDelimitedWriter::new(&mut buf);
        for batch in &resp.batches {
            row_count += batch.num_rows();
            writer.write_batches(&[batch])?;
        }
        writer.finish()?;
        c_print!("{}", std::str::from_utf8(&buf)?);
    } else if json_output {
        let mut buf = Vec::new();
        let mut writer = arrow::json::ArrayWriter::new(&mut buf);
        for batch in &resp.batches {
            row_count += batch.num_rows();
            writer.write_batches(&[batch])?;
        }
        writer.finish()?;
        c_print!("{}", std::str::from_utf8(&buf)?);
    } else {
        let mut table = Table::new_styled();
        table.set_styled_header(
            resp.schema
                .fields()
                .iter()
                .map(|col| col.name().to_uppercase())
                .collect::<Vec<String>>(),
        );

        let format_options = FormatOptions::default().with_display_error(true);
        for batch in &resp.batches {
            let formatters = batch
                .columns()
                .iter()
                .map(|c| ArrayFormatter::try_new(c.as_ref(), &format_options))
                .collect::<Result<Vec<_>, ArrowError>>()?;

            for row in 0..batch.num_rows() {
                let mut cells = Vec::new();
                for formatter in &formatters {
                    cells.push(Cell::new(formatter.value(row)));
                }
                table.add_row(cells);
            }
        }

        row_count = table.row_count();
        // Only print if there are actual results.
        if row_count > 0 {
            c_println!("{}", table);
            c_println!();
        }
    }

    c_eprintln!(
        "{} rows. Query took {:?}",
        row_count,
        Styled(Style::Notice, start_time.elapsed())
    );
    Ok(())
}

fn run_tables() -> Result<()> {
    let tables: Vec<TableItem> = SQL_TABLES
        .iter()
        .map(|t| TableItem {
            name: t.name,
            columns: t.columns.len(),
            description: first_line(t.description),
        })
        .collect();

    let mut f = Formatter::new();
    f.list("tables", &tables)?;
    if let Some(table) = SQL_TABLES.first() {
        f.next_step(
            &format!("restate sql describe {}", table.name),
            "see a table's columns",
        );
    }
    f.finish()
}

/// A `sql tables` row: name and column count, with the description (when set) as a detail.
#[derive(Serialize)]
struct TableItem {
    name: &'static str,
    columns: usize,
    description: &'static str,
}

impl ListItem for TableItem {
    const HEADERS: &'static [&'static str] = &["name", "columns"];

    fn columns(&self) -> Vec<Field> {
        vec![Field::new(self.name), Field::new(self.columns)]
    }

    fn details(&self) -> Vec<String> {
        if self.description.is_empty() {
            Vec::new()
        } else {
            vec![self.description.to_owned()]
        }
    }
}

fn run_describe(table_name: &str) -> Result<()> {
    let Some(doc) = SQL_TABLES.iter().find(|t| t.name == table_name) else {
        let valid = SQL_TABLES
            .iter()
            .map(|t| t.name)
            .collect::<Vec<_>>()
            .join(", ");
        bail!("Unknown table '{table_name}'. Valid tables: {valid}");
    };

    let rows: Vec<Vec<Field>> = doc
        .columns
        .iter()
        .map(|c| {
            vec![
                Field::new(c.name),
                Field::new(c.ty),
                Field::new(c.description),
            ]
        })
        .collect();

    let mut f = Formatter::new();
    f.detail(
        "table",
        &[
            ("name", Field::new(doc.name)),
            ("description", Field::new(doc.description)),
        ],
    );
    f.table("columns", &["name", "type", "description"], &rows);
    f.next_step(
        &format!("restate sql \"SELECT * FROM {} LIMIT 10\"", doc.name),
        "sample its rows",
    );
    f.finish()
}

/// Returns the first non-empty line of a (possibly multi-line) description.
fn first_line(description: &str) -> &str {
    description
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .unwrap_or("")
}
